# Generated by Django 2.2.1 on 2019-08-29 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(default='', max_length=30)),
                ('compound_id', models.CharField(max_length=30)),
                ('compound_act', models.DecimalField(decimal_places=2, max_digits=5)),
                ('features', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(default='', max_length=30)),
                ('compound_id', models.CharField(max_length=30)),
                ('features', models.TextField(default='')),
                ('protein_name', models.CharField(default='', max_length=30)),
                ('protein_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(default='', max_length=30)),
                ('protein_id', models.CharField(max_length=30)),
            ],
        ),
    ]
