# Generated by Django 2.2.1 on 2019-08-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merckchallengeapp', '0002_author_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
