# Generated by Django 2.2.1 on 2019-08-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merckchallengeapp', '0004_auto_20190829_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compound',
            name='compound_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
